version: '2.1'

networks:
  wordpress:
  
volumes:
  wordpress:
  nginx:
  mariadb:
  
services:
  wordpress_nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./wordpress:/var/www/html
    networks:
      - wordpress
    ports:
      - '92:80' 

  wordpress_mariadb:
    image: mariadb:latest
    container_name: wordpress_mariadb
    restart: unless-stopped
    env_file: wordpress_db.env
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - wordpress     
    expose:
      - '3306' 
      
  wordpress_redis:
    image: redis:latest
    container_name: wordpress_redis
    restart: unless-stopped
    networks:
      - wordpress
    expose:
      - '6379'

  wordpress:
    image: wordpress:6.0.3-php8.1-fpm
    container_name: wordpress_wordpress
    restart: unless-stopped
    env_file: wordpress.env
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress_nginx
      - wordpress_redis
      - wordpress_mariadb      
    networks:
      - wordpress
    expose:
      - '9000'
